name: Run Signal Bot

on:
  schedule:
    - cron: '*/15 * * * *'  # Run every 15 minutes
  workflow_dispatch:        # Manual run always available

jobs:
  signal:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Cache pip dependencies to speed up workflow
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests ccxt pandas feedparser

      # Run Signal Bot with retries and logging
      - name: Run Signal Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          for i in {1..3}; do
            echo "Attempt $i..."
            timeout 180 python smart_signal_advanced.py && break
            echo "Retrying in 15 seconds..."
            sleep 15
          done
