name: Run Signal Bot

on:
  schedule:
    - cron: '*/15 * * * *'  # run every 15 minutes
  workflow_dispatch:        # allows manual run

jobs:
  signal:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install dependencies
      - name: Install dependencies
        run: pip install --upgrade pip
      - run: pip install requests ccxt pandas

      # Run Signal Bot
      - name: Run Signal Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python smart_signal_advanced.py
